[book]
title = "OpenDB Documentation"
authors = ["Muhammad Fiaz <contact@muhammadfiaz.com>"]
description = "Documentation for OpenDB - A high-performance hybrid embedded database"
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/muhammad-fiaz/OpenDB"
git-repository-icon = "fa-github"
site-url = "/opendb/"

[output.html.fold]
enable = true
level = 1
